name: Build a Docker image

on:
  push:
    branches: ["main"]
    
  workflow_dispatch:
  
env:
  TAG: v1
  NAME: reactapp
  FILE: ractapp/Dockerfile
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
#       - name: Install node
#         uses: actions/setup-node@v3.0.0
#         with:
#           node-version: '16.14.0'
          
      - name: Docker Image
        run: docker build . --file ${{env.FILE}} --tag ${{env.NAME}}:${{env.TAG}}
        
        
          
      
          
