name: Build a Docker image

on:
  push:
    branches: ["main"]
    
  workflow_dispatch:
  
env:
  TAG: v1
  NAME: reactapp
  FILE: reactapp/
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Image
        working-directory: ${{env.FILE}}
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/${{env.NAME}}:${{env.TAG}}
      - name: Push Docker Image
        run: docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin ${{secrets.DOCKER_PASSWORD}}  && docker push ${{secrets.DOCKER_USERNAME}}/${{env.NAME}}:${{env.TAG}}

        
        
          
      
          
